#ifndef OPENGL_HPP
#define OPENGL_HPP

#include "glcorearb.h"

#define OPENGL_FUNC_LIST(MACRO)\
	MACRO(PFNGLCLEARCOLORPROC,glClearColor)\
	MACRO(PFNGLCLEARPROC,glClear)

#define OPENGL_DECLARE_FUNC(TYPE,NAME) inline TYPE NAME;
OPENGL_FUNC_LIST(OPENGL_DECLARE_FUNC)
#undef OPENGL_DECLARE_FUNC

#endif
