#ifndef OPENGL_HPP
#define OPENGL_HPP

#include "glcorearb.h"

#define OPENGL_FUNC_LIST(MACRO)\
	MACRO(PFNGLGETINTEGER64VPROC,glGetInteger64v)\
	MACRO(PFNGLCLEARCOLORPROC,glClearColor)\
	MACRO(PFNGLCLEARDEPTHPROC,glClearDepth)\
	MACRO(PFNGLCLEARPROC,glClear)\
	MACRO(PFNGLCULLFACEPROC,glCullFace)\
	MACRO(PFNGLFRONTFACEPROC,glFrontFace)\
	MACRO(PFNGLCREATESHADERPROC,glCreateShader)\
	MACRO(PFNGLDELETESHADERPROC,glDeleteShader)\
	MACRO(PFNGLSHADERSOURCEPROC,glShaderSource)\
	MACRO(PFNGLCOMPILESHADERPROC,glCompileShader)\
	MACRO(PFNGLATTACHSHADERPROC,glAttachShader)\
	MACRO(PFNGLDETACHSHADERPROC,glDetachShader)\
	MACRO(PFNGLGETSHADERIVPROC,glGetShaderiv)\
	MACRO(PFNGLGETSHADERINFOLOGPROC,glGetShaderInfoLog)\
	MACRO(PFNGLCREATEPROGRAMPROC,glCreateProgram)\
	MACRO(PFNGLDELETEPROGRAMPROC,glDeleteProgram)\
	MACRO(PFNGLLINKPROGRAMPROC,glLinkProgram)\
	MACRO(PFNGLGETPROGRAMIVPROC,glGetProgramiv)\
	MACRO(PFNGLGETPROGRAMINFOLOGPROC,glGetProgramInfoLog)\
	MACRO(PFNGLUSEPROGRAMPROC,glUseProgram)\
	MACRO(PFNGLGETUNIFORMLOCATIONPROC,glGetUniformLocation)\
	MACRO(PFNGLVIEWPORTPROC,glViewport)\
	MACRO(PFNGLENABLEPROC,glEnable)\
	MACRO(PFNGLDISABLEPROC,glDisable)\
	MACRO(PFNGLDEPTHFUNCPROC,glDepthFunc)\
	MACRO(PFNGLDEPTHMASKPROC,glDepthMask)\
	MACRO(PFNGLGENBUFFERSPROC,glGenBuffers)\
	MACRO(PFNGLDELETEBUFFERSPROC,glDeleteBuffers)\
	MACRO(PFNGLBINDBUFFERPROC,glBindBuffer)\
	MACRO(PFNGLBUFFERDATAPROC,glBufferData)\
	MACRO(PFNGLBUFFERSUBDATAPROC,glBufferSubData)\
	MACRO(PFNGLGETBUFFERPARAMETERIVPROC,glGetBufferParameteriv)\
	MACRO(PFNGLGETBUFFERPARAMETERI64VPROC,glGetBufferParameteri64v)\
	MACRO(PFNGLENABLEVERTEXATTRIBARRAYPROC,glEnableVertexAttribArray)\
	MACRO(PFNGLVERTEXATTRIBPOINTERPROC,glVertexAttribPointer)\
	MACRO(PFNGLGENVERTEXARRAYSPROC,glGenVertexArrays)\
	MACRO(PFNGLDELETEVERTEXARRAYSPROC,glDeleteVertexArrays)\
	MACRO(PFNGLBINDVERTEXARRAYPROC,glBindVertexArray)\
	MACRO(PFNGLDRAWARRAYSPROC,glDrawArrays)\
	MACRO(PFNGLDRAWARRAYSINSTANCEDPROC,glDrawArraysInstanced)\
	MACRO(PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC,glDrawArraysInstancedBaseInstance)\
	MACRO(PFNGLGETATTRIBLOCATIONPROC,glGetAttribLocation)\
	MACRO(PFNGLGENTEXTURESPROC,glGenTextures)\
	MACRO(PFNGLDELETETEXTURESPROC,glDeleteTextures)\
	MACRO(PFNGLBINDTEXTUREPROC,glBindTexture)\
	MACRO(PFNGLTEXPARAMETERIPROC,glTexParameteri)\
	MACRO(PFNGLTEXIMAGE2DPROC,glTexImage2D)\
	MACRO(PFNGLTEXIMAGE3DPROC,glTexImage3D)\
	MACRO(PFNGLTEXSUBIMAGE3DPROC,glTexSubImage3D)\
	MACRO(PFNGLACTIVETEXTUREPROC,glActiveTexture)\
	MACRO(PFNGLUNIFORM1IPROC,glUniform1i)\
	MACRO(PFNGLUNIFORM1IVPROC,glUniform1iv)\
	MACRO(PFNGLUNIFORMMATRIX4FVPROC,glUniformMatrix4fv)\
	MACRO(PFNGLGETUNIFORMBLOCKINDEXPROC,glGetUniformBlockIndex)\
	MACRO(PFNGLUNIFORMBLOCKBINDINGPROC,glUniformBlockBinding)\
	MACRO(PFNGLBINDBUFFERBASEPROC,glBindBufferBase)\
	MACRO(PFNGLMAPBUFFERPROC,glMapBuffer)\
	MACRO(PFNGLUNMAPBUFFERPROC,glUnmapBuffer)\
	MACRO(PFNGLISPROGRAMPROC,glIsProgram)\
	MACRO(PFNGLISBUFFERPROC,glIsBuffer)\
	MACRO(PFNGLISVERTEXARRAYPROC,glIsVertexArray)\
	MACRO(PFNGLISTEXTUREPROC,glIsTexture)\
	MACRO(PFNGLDEBUGMESSAGECONTROLPROC,glDebugMessageControl)\
	MACRO(PFNGLDEBUGMESSAGECALLBACKPROC,glDebugMessageCallback)

#define OPENGL_DECLARE_FUNC(TYPE,NAME) inline TYPE NAME;
OPENGL_FUNC_LIST(OPENGL_DECLARE_FUNC)
#undef OPENGL_DECLARE_FUNC

#endif
