#ifndef OPENGL_HPP
#define OPENGL_HPP

#include "glcorearb.h"

#define OPENGL_FUNC_LIST(MACRO)\
	MACRO(PFNGLCLEARCOLORPROC,glClearColor)\
	MACRO(PFNGLCLEARDEPTHPROC,glClearDepth)\
	MACRO(PFNGLCLEARPROC,glClear)\
	MACRO(PFNGLCULLFACEPROC,glCullFace)\
	MACRO(PFNGLFRONTFACEPROC,glFrontFace)\
	MACRO(PFNGLCREATESHADERPROC,glCreateShader)\
	MACRO(PFNGLDELETESHADERPROC,glDeleteShader)\
	MACRO(PFNGLSHADERSOURCEPROC,glShaderSource)\
	MACRO(PFNGLCOMPILESHADERPROC,glCompileShader)\
	MACRO(PFNGLATTACHSHADERPROC,glAttachShader)\
	MACRO(PFNGLDETACHSHADERPROC,glDetachShader)\
	MACRO(PFNGLGETSHADERIVPROC,glGetShaderiv)\
	MACRO(PFNGLGETSHADERINFOLOGPROC,glGetShaderInfoLog)\
	MACRO(PFNGLCREATEPROGRAMPROC,glCreateProgram)\
	MACRO(PFNGLDELETEPROGRAMPROC,glDeleteProgram)\
	MACRO(PFNGLLINKPROGRAMPROC,glLinkProgram)\
	MACRO(PFNGLGETPROGRAMIVPROC,glGetProgramiv)\
	MACRO(PFNGLGETPROGRAMINFOLOGPROC,glGetProgramInfoLog)\
	MACRO(PFNGLUSEPROGRAMPROC,glUseProgram)\
	MACRO(PFNGLGETUNIFORMLOCATIONPROC,glGetUniformLocation)\
	MACRO(PFNGLVIEWPORTPROC,glViewport)\
	MACRO(PFNGLENABLEPROC,glEnable)\
	MACRO(PFNGLDISABLEPROC,glDisable)\
	MACRO(PFNGLDEPTHFUNCPROC,glDepthFunc)\
	MACRO(PFNGLDEPTHMASKPROC,glDepthMask)\
	MACRO(PFNGLGENBUFFERSPROC,glGenBuffers)\
	MACRO(PFNGLDELETEBUFFERSPROC,glDeleteBuffers)\
	MACRO(PFNGLBINDBUFFERPROC,glBindBuffer)\
	MACRO(PFNGLBUFFERDATAPROC,glBufferData)\
	MACRO(PFNGLBUFFERSUBDATAPROC,glBufferSubData)\
	MACRO(PFNGLENABLEVERTEXATTRIBARRAYPROC,glEnableVertexAttribArray)\
	MACRO(PFNGLVERTEXATTRIBPOINTERPROC,glVertexAttribPointer)\
	MACRO(PFNGLGENVERTEXARRAYSPROC,glGenVertexArrays)\
	MACRO(PFNGLDELETEVERTEXARRAYSPROC,glDeleteVertexArrays)\
	MACRO(PFNGLBINDVERTEXARRAYPROC,glBindVertexArray)\
	MACRO(PFNGLDRAWARRAYSPROC,glDrawArrays)\
	MACRO(PFNGLGETATTRIBLOCATIONPROC,glGetAttribLocation)

#define OPENGL_DECLARE_FUNC(TYPE,NAME) inline TYPE NAME;
OPENGL_FUNC_LIST(OPENGL_DECLARE_FUNC)
#undef OPENGL_DECLARE_FUNC

#endif
